//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN.Model
{
    using RTree;
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class DataPoint
    {
        public bool compareTo(DataPoint point)
        {
            return this.rating >= point.rating && this.star >= point.star;
        }
        public DataPoint(double? rating, double? star)
        {
            this.rating = rating;
            this.star = star;
        }
        public DataPoint(Rectangle rectangle)
        {
            this.rating = rectangle.get(0).GetValueOrDefault().max;
            this.star   = rectangle.get(1).GetValueOrDefault().max;
        }
        public DataPoint() { }
        public int id { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<double> star { get; set; }
    }
}
