//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATN.Model
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    //weight vectoer include 2 element star and rating. 
    //Default star is left element, rating is right element
    public partial class WeightVector
    {
        public WeightVector()
        {
        }

        public WeightVector(double? rating, double? star)
        {
            this.star = star;
            this.rating = rating;
        }
        
        public int id { get; set; }
        public Nullable<double> star { get; set; }
        public Nullable<double> rating { get; set; }
    }
}
